### PR TITLE
Update Code to 1.87.0

### PR DESCRIPTION
**Pull request by benz0li**
Fixes https://github.com/coder/code-server/issues/6694

### CODE REVIEW

**Comment by benz0li** [comment]
`code-server-4.22.0-rc.1-linux-amd64.tar.gz` with Code 1.87.0 is deployed at https://coder.jupyter.b-data.ch.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* web view

Workspaces and Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.9.100`
*  `ms-python.python@2024.2.0`

**Comment by benz0li** [comment]
Ping @code-asher.

Please review and let the checks run.

**Comment by benz0li** [comment]
Some warnings during `yarn build:vscode`: [yarn-build-vscode_warnings.txt](https://github.com/coder/code-server/files/14445206/yarn-build-vscode_warnings.txt)

**Review by code-asher — APPROVED** [review]
Looks great, thank you!

The warnings look harmless enough but maybe they are caused by a mismatch in Node versions since they updated the version of Node?  I will get us updated after merging this and see if it fixes the warnings.

**Edit**: nevermind, the version is not updated until 1.88.  But I will still take a look at the warnings.  Maybe we have the wrong version of `@types/node` installed.

**Comment by benz0li** [comment]
> maybe they are caused by a mismatch in Node versions

That may be the cause. I currently use node v18.19.1 – the latest version of Node v18.

**Pull request merged**
