### PR TITLE
Update Code to 1.84.2

### PR DESCRIPTION
**Pull request by benz0li**
Fixes https://github.com/coder/code-server/issues/6516

### CODE REVIEW

**Comment by benz0li** [comment]
Found and updated the commit for Code 1.84.2.

**Comment by bilogic** [comment]
Hi! Can merge soon? Thanks!

**Comment by benz0li** [comment]
@code-asher It would be great to have a release by the end of this week.

Thank you.

**Comment by code-asher** [comment]
Should be able to, I will be back tomorrow.

**Review by code-asher — APPROVED** [review]

**Comment by bilogic** [comment]
@code-asher can we have a release please? 🙏

**Comment by benz0li** [comment]
@code-asher Regarding https://github.com/coder/code-server/actions/runs/6884702807/job/18727700812#step:7:22: Python v3.12.0 is problematic.

Use an older macOS image that still provides Python v3.11.

**Comment by code-asher** [comment]
Ahh thanks!  I will look into downgrading.

**Comment by code-asher** [comment]
Weird, supposedly it is using macOS 12.6.9 but the last run that succeeded was actually a version higher, 12.7.  The run before that (also successful) used 12.6.9.  Maybe I can downgrade just Python.

**Comment by benz0li** [comment]
> Weird, supposedly it is using macOS 12.6.9 but the last run that succeeded was actually a version higher, 12.7. The run before that (also successful) used 12.6.9. Maybe I can downgrade just Python.

The last successful run used https://github.com/actions/runner-images/blob/macOS-12/20230921.4/images/macos/macos-12-Readme.md: Python3 3.11.5

https://github.com/coder/code-server/actions/runs/6884702807/job/18727700812#step:7:22 used https://github.com/actions/runner-images/blob/macOS-12/20231029.1/images/macos/macos-12-Readme.md: Python3 3.12.0

**Comment by code-asher** [comment]
All right, put out an RC, will promote tomorrow if no one reports anything amiss.

**Comment by benz0li** [comment]
I tested again with the release candidate. As far as code-server is concerned, everything seems to be fine.

I ran into https://github.com/randy3k/radian/issues/446, but that has nothing to do with this project.  
👉 Only Data Scientists using code-server + [R extension](https://open-vsx.org/extension/REditorSupport/r) + [radian](https://github.com/randy3k/radian) + [httpgd](https://github.com/nx10/httpgd) are affected.

**Comment by benz0li** [comment]
> Found and updated the commit for Code 1.84.2.

@microsoft also updated the commit for Code 1.84.2: https://github.com/microsoft/vscode/releases/tag/1.84.2

**Pull request merged**
