### PR TITLE
fix: CSP and webview errors

### LINKED ISSUE #5708: [Bug]: Run and Debug not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS:  macOS
- Remote OS: Linux
- Remote Architecture:
- `code-server --version`: 4.8.0

### Steps to Reproduce

1. Open javascript or python file
2. set break point
3. Run and Debug

### Expected

Stop at break point

### Actual

Nothing happen

### Logs

_No response_

### Screenshot/Video

_No response_

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Version 4.7.1 was fine.

### LINKED ISSUE #5710: [Bug]: Content Security Policy violations breaks various features
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome Version 106.0.5249.119
- Local OS: macOS
- Remote OS: ubuntu:22.04 docker image
- Remote Architecture: amd64
- `code-server --version`: 4.8.0

### Steps to Reproduce

1. Use the `Dockerfile` below with version `4.8.0` and `docker run -p3000:3000 ...`
2. Open the browser console and access code-server on `127.0.0.1:3000`
3. You should see some CSP errors in the console.
4. When you open a new Jupyter Notebook, you can see it being really broken.

If you use code-server version 4.7.1 there are no CSP violations. So something about CSP must have changed in this version.
Also I have a small suspicion that the issue https://github.com/coder/code-server/issues/5708 is related to this.

```
FROM ubuntu:22.04
USER root
RUN apt-get update && apt install -y curl

#RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.7.1
RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.8.0

RUN code-server --force --install-extension ms-python.python --disable-telemetry --disable-update-check
RUN code-server --force --install-extension ms-toolsai.jupyter --disable-telemetry --disable-update-check

EXPOSE 3000
ENTRYPOINT code-server --bind-addr 0.0.0.0:3000 --force --disable-telemetry --disable-update-check --auth none /root/
```

### Expected

No CSP violations

### Actual

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'sha256-wwaDxsm1+SKIUb5YJXiZlYMyV7QPB8+zd6HPcTjigZs=' https:". Either the 'unsafe-inline' keyword, a hash ('sha256-TkIM/TmudlFEe0ZRp0ptvN54LClwk30Rql4ZPE0hm/I='), or a nonce ('nonce-...') is required to enable inline execution.

:3000/stable-129500ee4c8ab7263461ffe327268ba56b9f210d/static/out/vs/workbench/contrib/webview/browser/pre/index.html?id=24c70c6b-57f1-4f62-952d-03f0a65b434b&origin=24c70c6b-57f1-4f62-952d-03f0a65b434b&swVersion=4&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=http%3A%2F%2F127.0.0.1%3A3000&remoteAuthority=127.0.0.1%3A3000:18 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'sha256-wwaDxsm1+SKIUb5YJXiZlYMyV7QPB8+zd6HPcTjigZs=' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-IZkGO4jZeUn7pzM6pBZCZc9bUYm8oVNV3z8zEa8gxlk='), or a nonce ('nonce-...') is required to enable inline execution.

index.html:18 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'sha256-wwaDxsm1+SKIUb5YJXiZlYMyV7QPB8+zd6HPcTjigZs=' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-IZkGO4jZeUn7pzM6pBZCZc9bUYm8oVNV3z8zEa8gxlk='), or a nonce ('nonce-...') is required to enable inline execution.
```

### Logs

_No response_

### Screenshot/Video

image

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I have tested this served over https and with the docker setup on localhost as described in this issue.

Sorry I cannot pinpoint the issue better. I'm not familiar with the codebase.

### LINKED ISSUE #5711: [Bug]: Broken extensions with code-server 4.8.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari 16.1
- Local OS: macOS 13.0 (Ventura)
- Remote OS: [Debian bullseye](https://hub.docker.com/_/debian)
- Remote Architecture: amd64
- `code-server --version`: 4.8.0 005fa87699b4b3c791bd97693400dd016a7ee315 with Code 1.72.1

### Steps to Reproduce

1. Go to https://vscode-r.jupyter.b-data.ch
2. Log in with your GitHub account
3. Click "Start My Server"
4. Select image `R (jupyterlab/r/base:test) + code-server`
5. Open code-server
6. Try to create an R terminal or create/edit a Jupyter Notebook

### Expected

"R: Create R terminal" is supposed to create an R terminal.  
ℹ️ `[YYYY-MM-DD hh:mm:ss.sss] [exthost] [info] ExtensionService#_doActivateExtension REditorSupport.r, startup: false, activationEvent: 'onCommand:r.createRTerm'`

When creating a Jupyter Notebook it should be displayed and editable.

### Actual

No R terminal is created.

Jupyter Notebook is created but nothing is displayed.

### Logs

_No response_

### Screenshot/Video

_No response_

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

_No response_

### PR DESCRIPTION
**Pull request by jsjoeio**
## Description

When we released 4.8.0, we were using the wrong hash in two HTML files causing various issues related to webviews. This fixes it.

## Changes
- fix: update hashes in webview patch
- refactor: move parent-origin into webview

## TODOs
- [ ] add e2e test which uses Markdown preview
- [ ] modify test-extension to use extension webview and add test

fixes #5711
fixes #5710
fixes #5708

### CODE REVIEW

**Review by code-asher — APPROVED** [review]

**Comment by jsjoeio** [comment]
Decided we need to get this out ASAP so I will add tests later!

**Comment by jsjoeio** [comment]
We will publish a release candidate with a fix shortly (probably within the next 3-4 hours)

**Comment by achalagarwal** [comment]
@jsjoeio how do I use the install script to install a pre-release version?

**Comment by jsjoeio** [comment]
Apologies, that should be documented somewhere. I believe passing `--edge` should work. https://github.com/coder/code-server/blob/main/install.sh#L35-L36

**Comment by ZhengHui-Z** [comment]
> Apologies, that should be documented somewhere. I believe passing `--edge` should work. https://github.com/coder/code-server/blob/main/install.sh#L35-L36

code-server 4.16.1 94ef3776ad7bebfb5780dfc9632e04d20d5c9a6c  has the same error

**Comment by code-asher** [comment]
Hmm I am not seeing an issue on 4.16.1 using Chromium.  Are you able to consistently reproduce it?

**Comment by ZhengHui-Z** [comment]
> Hmm I am not seeing an issue on 4.16.1 using Chromium. Are you able to consistently reproduce it?

image

**Comment by code-asher** [comment]
Thank you for the screenshot!  Do you trigger this by opening a markdown preview or another way?  I have tried a few things (markdown preview, web extension, extension readmes, Jupyter extension) but nothing triggers it for me so  far.

Do you have any browser extensions installed?  I wonder if there is one trying to inject a script.

**Pull request merged**
