### PR TITLE
Update Code to 1.76.1

### LINKED ISSUE #6050: [Feat]: Upgrade Vscode to 1.76

### PR DESCRIPTION
**Pull request by code-asher**
- worker-src already contains blob so we can avoid patching that.
- localeService moved.
- Remaining changes were just line changes.
- Make language extensions installable again.
- Remove broken "install in browser" for language packs.
- Replace new locale import.

Closes #6050

### CODE REVIEW

**Comment by benz0li** [comment]
@code-asher I will continue to deploy release candidates to https://coder.jupyter.b-data.ch, test them manually and give feedback.

**Comment by code-asher** [comment]
Thank you!  I think this is about ready to go, I just need to confirm the display language still works.

**Comment by benz0li** [comment]
Unable to build an image for [v4.11.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.11.0-rc.1) with current extensions because of https://github.com/EclipseFdn/open-vsx.org/issues/1684.

**Comment by benz0li** [comment]
`code-server-4.11.0-rc.1-linux-amd64.tar.gz` from [Release v4.11.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.11.0-rc.1) is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.3.100`
*  `ms-python.python@2023.4.0`

---

Terminal is still not rendered properly because of https://github.com/xtermjs/xterm.js/issues/4120.  
ℹ️ Workaround: `"terminal.integrated.gpuAcceleration": "off"`

**Comment by benz0li** [comment]
@code-asher https://github.com/xtermjs/xterm.js/issues/4120 is resolved now: https://github.com/xtermjs/xterm.js/pull/4438.

Now it is just a matter of time until the fixed version is released, and updated [there](https://github.com/microsoft/vscode/blob/main/package.json#L91).

**Comment by code-asher** [comment]
Awesome news!!

**Comment by benz0li** [comment]
Regarding https://github.com/coder/code-server/pull/6070#issuecomment-1471564040:

> [...] that fix is coming in 1.78 with this PR https://github.com/microsoft/vscode/pull/178443.

– https://github.com/microsoft/vscode/issues/177754#issuecomment-1485692637

**Pull request merged**
