### PR TITLE
test: replace ts-jest with @swc-node/jest

### PR DESCRIPTION
**Pull request by F3n67u**
Fixes https://github.com/coder/code-server/issues/4403

### CODE REVIEW

**Review by jsjoeio — COMMENTED** [review]
Thank you for doing this! You're helping a ton and we appreciate it :D 

Two questions:
1. any chance you can update your description with some stats: how long did unit tests take before and how much faster are they? 
2. do we need to add a separate typechecking step? i originally chose `ts-jest` since it does typechecking on our tests. are we losing that now and need to add elsewhere?

**Comment by F3n67u** [comment]
From ci stat:

## @swc-node/jest:
```
Test Suites: 20 passed, 20 total
Tests:       207 passed, 207 total
Snapshots:   0 total
Time:        15.393 s
Ran all test suites.
Done in 20.30s.
```
https://github.com/coder/code-server/runs/6426594467?check_suite_focus=true#step:12:76

## ts-jest
```
Test Suites: 20 passed, 20 total
Tests:       207 passed, 207 total
Snapshots:   0 total
Time:        21.505 s
Ran all test suites.
Done in 27.95s.
```
https://github.com/coder/code-server/runs/6426871269?check_suite_focus=true#step:12:76

total unit test time is from 28s -> 20s，but because we lose the type check of `ts-jest`, I don't think the 8s is worth it.

our unit test suite is very small size, maybe we could reconsider switch to `@swc-node/jest` when our unit test grow to big enough.

@jsjoeio what do you think?

**Comment by jsjoeio** [comment]
@F3n67u thank you for taking the time to add that! Hmm...you're probably right. I thought it would be a greater savings to be honest. I agree though, might not make sense to add if we lose typechecking then.

Thoughts @code-asher?

**Comment by code-asher** [comment]
I think we should keep the type checking even if it does make things slower.

**Comment by jsjoeio** [comment]
Agreed.  I think it that case, let's close this PR and that issue. Is that okay with you @F3n67u? Thank you for doing this though! Really appreciate it.

**Comment by F3n67u** [comment]
> Agreed. I think it that case, let's close this PR and that issue. Is that okay with you @F3n67u? Thank you for doing this though! Really appreciate it.

yep. lets close this pr.

**Pull request closed without merging**
