### PR TITLE
Update Code to 1.80.1

### LINKED ISSUE #6316: [Feat]: Update Code to 1.80
## What is your suggestion?

Update Code to 1.80

### PR DESCRIPTION
**Pull request by benz0li**
Closes #6316

### CODE REVIEW

**Comment by benz0li** [comment]
`code-server-4.15.0-rc.1-linux-amd64.tar.gz` is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools-docker)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.3.100`
*  `ms-python.python@2023.12.0`

**Comment by code-asher** [comment]
I think maybe we just have to bump up the timeout on the build step.  Not sure why it seems to be taking longer than normal but oh well.

**Comment by benz0li** [comment]
> I think maybe we just have to bump up the timeout on the build step. Not sure why it seems to be taking longer than normal but oh well.

`yarn build:vscode` took 35 mins on my server (Intel® Xeon® Silver 4210R).

**Review by code-asher — APPROVED** [review]
Huzzah!

**Comment by benz0li** [comment]
`code-server-4.15.0-rc.1-linux-amd64.tar.gz` from [Release v4.15.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.15.0-rc.1) is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools-docker)`.

Test results are identical to https://github.com/coder/code-server/pull/6340#issuecomment-1639464721. @alexthillen Is flag `--trusted-origin` working as expected?

**Comment by alexthillen** [comment]
Yes. :)

**Comment by code-asher** [comment]
Thanks, all!  I will promote the release today.

**Pull request merged**
