### PR TITLE
Remove deprecated --link

### PR DESCRIPTION
**Pull request by code-asher**

### CODE REVIEW

**Comment by code-asher** [comment]
@benz0li I am making one more RC to squeeze this change in, then I am thinking we can do the regular release tomorrow morning.

**Comment by benz0li** [comment]
@code-asher Same outcome for [Release v4.10.0-rc.2](https://github.com/coder/code-server/releases/tag/v4.10.0-rc.2) as https://github.com/coder/code-server/pull/6004#issuecomment-1428488541.

@Tyriar Use image `R (base:test-devtools)` at https://coder.jupyter.b-data.ch/ for Code 1.75.1.  
ℹ️ Image R (jupyterlab/r/verse:latest-devtools) runs Code 1.73.1.

**Comment by code-asher** [comment]
@benz0li thank you again for all the testing help!!

**Comment by stpoa** [comment]
Why did you remove the `--link` option?

**Comment by code-asher** [comment]
The link servers have been shut down so the flag no longer works.

**Pull request merged**
