### PR TITLE
Re-fix #2767

### LINKED ISSUE #2767: Cannot start stopped docker container, user 'coder' does not exist
- Web Browser:
- Local OS: MacOS
- Remote OS: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-123-generic x86_64)
- Remote Architecture:
- `code-server --version`: 3.9.0

I set up code-server with Docker as indicated in https://hub.docker.com/r/codercom/code-server

```
mkdir -p ~/.config
docker run -it --name code-server -p 127.0.0.1:8080:8080 \
  -v "$HOME/.config:/home/coder/.config" \
  -v "$PWD:/home/coder/project" \
  -u "$(id -u):$(id -g)" \
  -e "DOCKER_USER=$USER" \
  codercom/code-server:latest
```

The initial run works perfectly. I then stop the container using ctrl+c. When I try to start the container again using `docker start code-server` the container stops immediately. Running `docker logs code-server` outputs:

```
[2021-02-25T14:46:34.514Z] info  code-server 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b
[2021-02-25T14:46:34.516Z] info  Using user-data-dir ~/.local/share/code-server
[2021-02-25T14:46:34.537Z] info  Using config file ~/.config/code-server/config.yaml
[2021-02-25T14:46:34.538Z] info  HTTP server listening on http://0.0.0.0:8080 
[2021-02-25T14:46:34.538Z] info    - Authentication is enabled
[2021-02-25T14:46:34.538Z] info      - Using password from ~/.config/code-server/config.yaml
[2021-02-25T14:46:34.538Z] info    - Not serving HTTPS 
^Cusermod: user 'coder' does not exist
```

This issue seems to be related to [#2267](https://github.com/cdr/code-server/issues/2267), but I am still getting the user error message.

### PR DESCRIPTION
**Pull request by xfl12345**
[Cannot start stopped docker container, user 'coder' does not exist](https://github.com/coder/code-server/issues/2767)

### CODE REVIEW

**Comment by xfl12345** [comment]
The example of `docker-compose.yml` can be view as flow link.  
[https://github.com/xfl12345/docker-setup/blob/a100a69e8245ec7a1abb0ec9073a8cd1bcfa8096/compose/standalone/code_server/docker-compose.example.yml](https://github.com/xfl12345/docker-setup/blob/a100a69e8245ec7a1abb0ec9073a8cd1bcfa8096/compose/standalone/code_server/docker-compose.example.yml)

**Comment by xfl12345** [comment]
Reproduce:  

1. `docker compose up -d --remove-orphans`
2. Finish the WebUI setup
3. `docker restart code-server`

The log will be like as follow:  
```text
[2024-09-25T09:10:10.098Z] info  code-server 4.90.3 26c763485b9101fcae2ce56fc0903f0e2d48abe3
[2024-09-25T09:10:10.126Z] info  Using user-data-dir /root/.local/share/code-server
[2024-09-25T09:10:10.274Z] info  Using config file /root/.config/code-server/config.yaml
[2024-09-25T09:10:10.275Z] info  HTTP server listening on http://0.0.0.0:8080/
[2024-09-25T09:10:10.276Z] info    - Authentication is enabled
[2024-09-25T09:10:10.276Z] info      - Using password from /root/.config/code-server/config.yaml
[2024-09-25T09:10:10.277Z] info    - Not serving HTTPS
[2024-09-25T09:10:10.278Z] info  Session server listening on /root/.local/share/code-server/code-server-ipc.sock
[23:20:31] 




[23:20:31] Extension host agent started.
[23:20:35] Deleted uninstalled extension from disk eamodio.gitlens /root/.local/share/code-server/extensions/eamodio.gitlens-15.4.0-universal
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
usermod: user 'coder' does not exist
```

**Comment by xfl12345** [comment]
> Thank you for the PR!
> 
> Do you know what exactly causes the bug? I tried to reproduce with `docker compose` and then `docker restart` but it seems to be working without errors for me. Here is what I ended up with:
> 
> ```
> # version: '3'
> services:
>   code_server:
>     env_file:
>       - path: ./default.env
>         required: true
>     container_name: code-server
>     image: codercom/code-server:latest-xfl
>     pull_policy: build
>     build:
>       context: ./
>       dockerfile: code-server-xfl.Dockerfile
>     user: "1000:1000"
>     volumes:
>       - /home/coder/.local:/home/coder/.local
>       - /home/coder/.config:/home/coder/.config
>     extra_hosts:
>       - "host.docker.internal:host-gateway"
>     restart: always
> ```
> 
> Maybe it is the `user` line? I used `1000` because I do not have a `2006` user. But I am not sure why it would matter.
> 
> It seems like the way for the bug to trigger is if `whoami` returned something other than `code-server` but it is not clear to me when or why this would happen.

You can try to create another normal user with UID not equal to `1000`.  
Maybe ·code-server· is not recommended(or not supported?) to use a UID that is different from `1000`?  
But it works fine with the patch applied.

**Comment by xfl12345** [comment]
I noticed that `code-server` was running as root when I specified a UID different from `1000`.  
It seems that some function is broken after taking that action.  

Perhaps `code-server` does not support using a custom UID.  
So, I closed the PR.

**Comment by xfl12345** [comment]
I found the reason for "running as root" because I defined `docker-compose.yml` as below.

```yaml
services:
  code_server:
    extends:
      file: ./docker-compose.example.yml
      service: code_server
    user: root
    pid: host
    ipc: host
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
```

Then I disabled some features by commenting out some fields.  


```yaml
services:
  code_server:
    extends:
      file: ./docker-compose.example.yml
      service: code_server
    # user: root
    # pid: host
    # ipc: host
    # cap_add:
    #  - ALL
    security_opt:
      - apparmor=unconfined
```

I'm sure that the patch fix the problem.

**Comment by xfl12345** [comment]
> Ohh interesting! If it runs as root, is that a sign that something else is wrong?
> 
> Either way, it seems reasonable to use `id` to detect if the user already exists. I think we probably do not need the `whoami` call at all if we do it that way. Would this work?
> 
> ```shell
> # Rename coder user to the name in DOCKER_USER if DOCKER_USER does not already exist.
> if ! id -u "$DOCKER_USER" 2>/dev/null ; then
> ```

Because the command will print the UID when it begins to check, I have replaced it with the code as below.
```bash
if [ -z "$(id -u "$DOCKER_USER" 2>/dev/null)" ]; then
```

Test case:  

1. UID[2006], name[code-server]
    - First run: OK
    - Restart: OK
2. UID[2006], name[xfl12345]
    - First run: OK
    - Restart: OK
3. UID[2006], name not set
    - First run: OK
    - Restart: OK
4. UID[1000], name not set
    - First run: OK
    - Restart: OK
4. UID[1000], name[coder]
    - First run: OK
    - Restart: OK
5. UID[1000], name[xfl12345]
    - First run: OK
    - Restart: OK
6. UID[0], name not set
    - First run: OK
    - Restart: OK
7. UID[0], name[code-server]
    - First run: OK
    - Restart: OK
8. UID[0], name[root]
    - First run: OK
    - Restart: OK

ALL PASSED! Cheers!

**Comment by code-asher** [comment]
Sorry for the delay, thank you for fixing this!

**Pull request merged**
