### PR TITLE
Add telemetry and option to disable

### PR DESCRIPTION
**Pull request by kylecarbs**
Enables telemetry with default VS Code events being tracked.

Adds `--disable-telemetry` flag and `DISABLE_TELEMETRY` env variable making an extremely easy opt-out.

### CODE REVIEW

**Review by ammario — APPROVED** [review]

**Comment by illiapoplawski** [comment]
When you included the changes from pr [422](https://github.com/codercom/code-server/pull/422) the change that I mentioned didn't get added to this pr.

>Just noticed doc/self-hosted/index.md also mentions the code-server -h help option at bottom.

>Use code-server -h or code-server --help to view the usage for the cli. This is also shown at the beginning of this section.

>should read:

>Use code-server --help to view the usage for the cli. This is also shown at the beginning of this section.

**Comment by kylecarbs** [comment]
@illiapoplawski fixed!

**Review by code-asher — APPROVED** [review]

**Comment by NHollmann** [comment]
It would be nice if there were more details on telemetry. I know, I can disable it, but if I knew what exactly is sent I would consider turning it back on. 🤔

**Comment by deansheather** [comment]
@NHollmann:

- Machine ID (generated by code-server and cached if there's no OS machine ID)
- CPU core count, model
- Memory usage, total memory
- Shell (bash, zsh, etc.)
- OS release and arch

Along with any information VSCode telemetry sends by default which is documented thoroughly in their source: Microsoft/vscode#34997.

**Review by Naxhieli84 — APPROVED** [review]

**Review by khanimehdi117-rgb — APPROVED** [review]

**Comment by hackingbyjamesgarrett-hue** [comment]
> When you included the changes from pr [422](https://github.com/codercom/code-server/pull/422) the change that I mentioned didn't get added to this pr.
> 
> > Just noticed doc/self-hosted/index.md also mentions the code-server -h help option at bottom.
> 
> > Use code-server -h or code-server --help to view the usage for the cli. This is also shown at the beginning of this section.
> 
> > should read:
> 
> > Use code-server --help to view the usage for the cli. This is also shown at the beginning of this section.

Delete

**Pull request merged**
