### PR TITLE
chore: update Code to 1.73.1

### LINKED ISSUE #5768: [Feat]: upgrade to 1.73.1

### PR DESCRIPTION
**Pull request by jsjoeio**
Fixes #5768 

image

### CODE REVIEW

**Review by code-asher — APPROVED** [review]

**Comment by benz0li** [comment]
I have tested code-server [v4.9.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.9.0-rc.1):

JupyterHub log:

```
[...]
The factory function of "vs/platform/product/common/product" has thrown an exception
Error: EACCES: permission denied, open '/opt/code-server/lib/vscode/product.json'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1215:22)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.require._load (/opt/code-server/out/node/plugin.js:54:74)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Function.r [as __$__nodeRequire] (/opt/code-server/lib/vscode/out/vs/loader.js:5:101)
    at Object.<anonymous> (/opt/code-server/lib/vscode/out/vs/server/node/server.main.js:88:60032)
    at Function.s._safeInvokeFunction (/opt/code-server/lib/vscode/out/vs/loader.js:5:1337)
    at Function.s._invokeFactory (/opt/code-server/lib/vscode/out/vs/loader.js:5:1522)
    at s.complete (/opt/code-server/lib/vscode/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/opt/code-server/lib/vscode/out/vs/loader.js:6:1112)
    at s._resolve (/opt/code-server/lib/vscode/out/vs/loader.js:6:510)
    at s.defineModule (/opt/code-server/lib/vscode/out/vs/loader.js:5:6066)
    at y (/opt/code-server/lib/vscode/out/vs/loader.js:6:1825)
    at h (/opt/code-server/lib/vscode/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/opt/code-server/lib/vscode/out/vs/server/node/server.main.js:88:59568)
    at Object.<anonymous> (/opt/code-server/lib/vscode/out/vs/server/node/server.main.js:185:2106)
    at e._createAndEvalScript (/opt/code-server/lib/vscode/out/vs/loader.js:4:2598)
    at /opt/code-server/lib/vscode/out/vs/loader.js:4:2237
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/code-server/lib/vscode/product.json',
  phase: 'factory',
  moduleId: 'vs/platform/product/common/product',
  neededBy: []
}
[...]
```

Furter information:

```bash
$ ls -al /opt/code-server/lib/vscode
total 168
drwxr-xr-x   7 root root  4096 Nov 10 21:52 .
drwxr-xr-x   3 root root  4096 Nov 10 21:52 ..
drwxr-xr-x   4 root root  4096 Nov 10 20:59 bin
drwxr-xr-x 104 root root  4096 Nov 11 07:48 extensions
drwxr-xr-x 107 root root  4096 Oct 25 19:13 node_modules
lrwxrwxrwx   1 root root    12 Nov 10 21:52 node_modules.asar -> node_modules
-rw-r--r--   1 root root 91042 Nov 10 21:00 npm-shrinkwrap.json
drwxr-xr-x   3 root root  4096 Nov 10 20:59 out
-rw-r--r--   1 root root  1222 Nov 10 21:00 package.json
-rw-------   1 root root  3813 Nov 10 21:49 product.json
drwxr-xr-x   3 root root  4096 Nov 10 20:59 resources
-rw-r--r--   1 root root 38322 Nov 10 21:00 yarn.lock
```

👉 `product.json` should have permissions `644` not `600`.

**Comment by benz0li** [comment]
So I fixed the above; but then, the Terminal was not working:

Browser console:

```
[Error] TypeError: undefined is not an object (evaluating 'l._renderService.dimensions?.css.cell')
	getFont (workbench.web.main.js:3249:11305)
	_getDimension (workbench.web.main.js:3141:42098)
	_evaluateColsAndRows (workbench.web.main.js:3141:41211)
	layout (workbench.web.main.js:3144:2598)
	layout (workbench.web.main.js:3141:10188)
	layout (workbench.web.main.js:163:20741)
	layoutViews (workbench.web.main.js:163:34590)
	layout (workbench.web.main.js:163:26726)
	layout (workbench.web.main.js:3141:9115)
	layout (workbench.web.main.js:3141:16920)
	forEach
	layout (workbench.web.main.js:163:20741)
	layoutViews (workbench.web.main.js:163:34590)
	layout (workbench.web.main.js:163:26726)
	layout (workbench.web.main.js:2304:13600)
	layoutBody (workbench.web.main.js:3172:14145)
	layout (workbench.web.main.js:226:18534)
	layout (workbench.web.main.js:163:20741)
	layoutViews (workbench.web.main.js:163:34590)
	layout (workbench.web.main.js:163:26726)
	layout (workbench.web.main.js:226:23905)
	layout (workbench.web.main.js:3045:46287)
	layout (workbench.web.main.js:3045:69293)
	layout (workbench.web.main.js:2148:15766)
	layout (workbench.web.main.js:3052:6954)
	layout (workbench.web.main.js:3052:13074)
	_layout (workbench.web.main.js:163:53899)
	layout (workbench.web.main.js:163:53660)
	layout (workbench.web.main.js:163:20741)
	layoutViews (workbench.web.main.js:163:34590)
	layout (workbench.web.main.js:163:26726)
	layout (workbench.web.main.js:163:45387)
	layout (workbench.web.main.js:163:20741)
	layoutViews (workbench.web.main.js:163:34590)
	layout (workbench.web.main.js:163:26726)
	layout (workbench.web.main.js:163:45387)
	layout (workbench.web.main.js:163:20741)
	layoutViews (workbench.web.main.js:163:34590)
	layout (workbench.web.main.js:163:26726)
	layout (workbench.web.main.js:163:45387)
	layout (workbench.web.main.js:163:56258)
	layout (workbench.web.main.js:163:65949)
	layout (workbench.web.main.js:163:70368)
	layout (workbench.web.main.js:3123:32080)
	(anonymous function) (workbench.web.main.js:1808:37462)
```

**Comment by benz0li** [comment]
@jsjoeio code-server [v4.9.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.9.0-rc.1) (with `CS_DISABLE_GETTING_STARTED_OVERRIDE=1` set) is deployed at https://vscode-r.jupyter.b-data.ch; Image `R (base:test) + code-server`.

Functionality [modified by patches] tested and found to work:

* base-path
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

👉 I could not test cli-window-open as the Terminal was not working.

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2022.10.110`
*  `ms-python.python@2022.16.1`

**Comment by jsjoeio** [comment]
@benz0li thank you for testing. I see the Terminal error but I'm not sure what's causing it  🤔 @code-asher and I will have to dig in. Thanks for helping test!

image

**Pull request merged**
