### PR TITLE
Add VSCODE_PROXY_URI env var to extension host and terminal

### PR DESCRIPTION
**Pull request by code-asher**
## Checklist

- [x] Update `CHANGELOG.md`
- [x] Get proxy path from the client instead of `req.headers.host`.
- [X] Expose VSCODE_PROXY_URI to plugins
- [x] Expose VSCODE_PROXY_URI to terminal

### CODE REVIEW

**Comment by code-asher** [comment]
Currently on hold since I will need to rebase this on 1.57.

**Comment by jsjoeio** [comment]
@code-asher remind me and @jawnsy that we should write a test for the webview fix we did here: https://github.com/cdr/code-server/pull/3895

**Comment by jsjoeio** [comment]
bump @code-asher - anything I can do to help get these unblocked and ready to merge?

**Comment by code-asher** [comment]
Uh I forgot about this, I'll rebase today.

**Comment by jsjoeio** [comment]
@code-asher and I spoke offline about this. If we can get this in this week before Wednesday, great! But most likely shooting for the next release.

**Comment by jsjoeio** [comment]
bump @code-asher -> think we'll be able to get this PR rebased, updated and marked ready this week

**Comment by code-asher** [comment]
Tentatively yes.

**Comment by jsjoeio** [comment]
Man, we really need to fix https://github.com/cdr/code-server/issues/4027.

This is failing because your PR is from a fork (yet you're a maintainer and have access to `m`) 😢

image

**Comment by code-asher** [comment]
All good to go, blocked by a https://github.com/cdr/vscode/pull/3

**Comment by jsjoeio** [comment]
Besides the conflicting files, is there anything blocking this?

(Happy to pick it up as well)

**Comment by code-asher** [comment]
I think it is just conflicts.  I will get it sorted on Monday!

**Comment by jsjoeio** [comment]
Let me know if you need help moving this forward!

**Comment by jsjoeio** [comment]
Too many changes and branch out-of-date. We'll see if we can get this ready for the next release.

**Comment by jsjoeio** [comment]
@code-asher what do you think about this PR? Is it at the end of it's life?

**Comment by code-asher** [comment]
I think we can rebase it once 4.0.0 is stable.

**Comment by code-asher** [comment]
I will re-open this when it is ready to go.

**Pull request closed without merging**
