### PR TITLE
Update Code to 1.86.2

### PR DESCRIPTION
**Pull request by benz0li**
Ping @code-asher

### CODE REVIEW

**Comment by benz0li** [comment]
`code-server-4.21.2-rc.1-linux-amd64.tar.gz` with Code 1.86.2 is deployed at https://coder.jupyter.b-data.ch.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* web view

Workspaces and Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.9.100`
*  `ms-python.python@2024.0.1`

**Review by code-asher — APPROVED** [review]
Awesome, thank you!

**Comment by iustin** [comment]
Any chance to release this soon?

**Comment by code-asher** [comment]
Oh...thank you for the ping, for some reason I thought I had already released this.  I will put it out today.

**Pull request merged**
