### PR TITLE
Update Code to 1.94.0

### PR DESCRIPTION
**Pull request by benz0li**
Fixes https://github.com/coder/code-server/issues/7018

---

yarn -> npm

- vscode: Seems like you are using `yarn` which is not supported in this repo any more, please use `npm i` instead.

### CODE REVIEW

**Comment by benz0li** [comment]
Notes:

```diff
--- lib/vscode/src/vs/platform/extensionManagement/node/extensionDownloader.ts
+++ lib/vscode/src/vs/platform/extensionManagement/node/extensionDownloader.ts
@@ -114,7 +114,10 @@ export class ExtensionsDownloader extend
 			return false;
 		}
 
+		return false
+		// @ts-expect-error
 		const value = this.configurationService.getValue('extensions.verifySignature');
+		// @ts-expect-error
 		return isBoolean(value) ? value : true;
 	}
```

👉 Code does not exist any more

---

```diff
--- lib/vscode/src/vs/workbench/contrib/remote/browser/remoteExplorer.ts
+++ lib/vscode/src/vs/workbench/contrib/remote/browser/remoteExplorer.ts
@@ -77,7 +77,7 @@ export class ForwardedPortsView extends
 	private async enableForwardedPortsView() {
 		this.contextKeyListener.clear();
 
-		const viewEnabled: boolean = !!forwardedPortsViewEnabled.getValue(this.contextKeyService);
+		const viewEnabled: boolean = true;
 
 		if (viewEnabled) {
 			const viewContainer = await this.getViewContainer();
```

ℹ️ Also `const featuresEnabled: boolean = true;`

---

```diff
--- lib/vscode/src/vs/workbench/workbench.web.main.ts
+++ lib/vscode/src/vs/workbench/workbench.web.main.ts
@@ -52,7 +52,7 @@ import 'vs/workbench/services/dialogs/br
 import 'vs/workbench/services/host/browser/browserHostService';
 import 'vs/workbench/services/lifecycle/browser/lifecycleService';
 import 'vs/workbench/services/clipboard/browser/clipboardService';
-import 'vs/workbench/services/localization/browser/localeService';
+import 'vs/workbench/services/localization/electron-sandbox/localeService';
 import 'vs/workbench/services/path/browser/pathService';
 import 'vs/workbench/services/themes/browser/browserHostColorSchemeService';
 import 'vs/workbench/services/encryption/browser/encryptionService';
@@ -118,8 +118,9 @@ registerSingleton(ILanguagePackService,
 // Logs
 import 'vs/workbench/contrib/logs/browser/logs.contribution';
 
-// Localization
-import 'vs/workbench/contrib/localization/browser/localization.contribution';
+// Localization.  This does not actually import anything specific to Electron so
+// it should be safe.
+import 'vs/workbench/contrib/localization/electron-sandbox/localization.contribution';
 
 // Performance
 import 'vs/workbench/contrib/performance/browser/performance.web.contribution';
```

👉 Code does not exist any more

**Comment by benz0li** [comment]
@code-asher Please review and migrate the CI from `yarn` to `npm`.

Thank you.

**Comment by benz0li** [comment]
@code-asher `npm run build:vscode` runs into the following error:

```
[hh:mm:ss] Error: /home/benz0li/projects/coder/code-server/lib/vscode/src/vs/platform/telemetry/test/browser/telemetryService.test.ts(20,31): Argument of type 'sinon.SinonStatic' is not assignable to parameter of type 'import("/home/benz0li/projects/coder/code-server/lib/vscode/node_modules/@types/sinon-test/node_modules/@types/sinon/index").SinonStatic'.
  Type 'SinonStatic' is not assignable to type 'SinonSandbox'.                                                         
    The types of 'usingPromise(...).replace' are incompatible between these types.                                     
      Property 'usingAccessor' is missing in type '<T, TKey extends keyof T, R extends T[TKey] = T[TKey]>(obj: T, prop: TKey, replacement: R) => R' but required in type 'SandboxReplace'.                                                    
[hh:mm:ss] Finished compilation with 1 errors after 3057276 ms
[hh:mm:ss] Error: /home/benz0li/projects/coder/code-server/lib/vscode/src/vs/platform/telemetry/test/browser/telemetryService.test.ts(20,31): Argument of type 'sinon.SinonStatic' is not assignable to parameter of type 'import("/home/benz0li/projects/coder/code-server/lib/vscode/node_modules/@types/sinon-test/node_modules/@types/sinon/index").SinonStatic'.
  Type 'SinonStatic' is not assignable to type 'SinonSandbox'.                                                         
    The types of 'usingPromise(...).replace' are incompatible between these types.                                     
      Property 'usingAccessor' is missing in type '<T, TKey extends keyof T, R extends T[TKey] = T[TKey]>(obj: T, prop: TKey, replacement: R) => R' but required in type 'SandboxReplace'.                                                    
[hh:mm:ss] Finished compilation with 1 errors after 3057277 ms                                                         
[hh:mm:ss] 'vscode-reh-web-linux-x64-min' errored after 51 min
[hh:mm:ss] Error: Found 1 errors                           
    at Stream.<anonymous> (/home/benz0li/projects/coder/code-server/lib/vscode/build/lib/reporter.js:91:29)            
    at _end (/home/benz0li/projects/coder/code-server/lib/vscode/node_modules/through/index.js:65:9)                   
    at stream.end (/home/benz0li/projects/coder/code-server/lib/vscode/node_modules/through/index.js:74:5)             
    at Stream.onend (node:internal/streams/legacy:48:10)   
    at Stream.emit (node:events:531:35)                    
    at Stream.emit (node:domain:551:15)                    
    at drain (/home/benz0li/projects/coder/code-server/lib/vscode/node_modules/through/index.js:34:23)                 
    at stream.queue.stream.push (/home/benz0li/projects/coder/code-server/lib/vscode/node_modules/through/index.js:45:5)                            
    at Stream.end (/home/benz0li/projects/coder/code-server/lib/vscode/node_modules/through/index.js:15:35)            
    at _end (/home/benz0li/projects/coder/code-server/lib/vscode/node_modules/through/index.js:65:9)                   
error Command failed with exit code 1.
```

**Comment by code-asher** [comment]
VS Code switched to npm??  Great news.  I will try to get to this today.

**Comment by benz0li** [comment]
> VS Code switched to npm??

Yes.

**Comment by benz0li** [comment]
@code-asher `Code - OSS` v1.94.1 was released today: https://github.com/microsoft/vscode/releases/tag/1.94.1

**Comment by benz0li** [comment]
@code-asher `Code - OSS` v1.94.2 was released today: https://github.com/microsoft/vscode/releases/tag/1.94.2

**Comment by code-asher** [comment]
Was not able to get back to this last week but am aiming to get it sorted today or maybe tomorrow.

**Comment by code-asher** [comment]
The entrypoint having been rewritten in ESM is making things really difficult, I started converting us to ESM but it is a nightmare.

Think tomorrow I am going to break out VS Code into a separate process and communicate via IPC rather than importing it directly in the same process, should completely isolate us from any changes VS Code makes like this, and is the way it really should have been done in the first place.

**Comment by benz0li** [comment]
> Think tomorrow I am going to break out VS Code into a separate process and communicate via IPC rather than importing it directly in the same process, should completely isolate us from any changes VS Code makes like this, and is the way it really should have been done in the first place.

Sounds like a major change. I will do more extensive testing with the release candidate, then.

**Comment by code-asher** [comment]
So, I got most of that done last night but, an you guessed it is getting pretty complicated.  I still think it is probably the right move long-term but for this release I think I will go with a simpler fix and just rewrite `server-main.js` as a CJS module.

**Comment by code-asher** [comment]
Actually I can just copy the old `server-main.js` from an older commit, I think, before it was converted to ESM.

**Comment by benz0li** [comment]
Ping @code-asher: `code-server-4.94.2-rc.1-linux-amd64.tar.gz` with Code 1.94.2 is deployed at https://coder.jupyter.b-data.ch.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* web view

Workspaces and Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2024.9.1`
*  `ms-python.python@2024.16.1`

ℹ️ Because of issue https://github.com/coder/code-server/issues/7042, these are not installed as built-in extensions.

Safari is unable to render the font (MesloLGS NF) properly:

safari-font

ℹ️ No problem with Firefox.

**Comment by benz0li** [comment]
I was able to reproduce the Terminal font issue in Codespaces and opened an [upstream issue](https://github.com/microsoft/vscode/issues/231725).

**Comment by benz0li** [comment]
> Sorry for the delay, I was out last week.

No worries.

> Thank you for opening that upstream!

👍 

> Hmm that extension installation issue sounds like a release blocker.

Yes.

**Pull request merged**
