### PR TITLE
fix(Install.sh): Add single qoutes to correctly create the dir

### PR DESCRIPTION
**Pull request by KozmikNano**
# Fixes

- Fixes an issue where creating a folder in the standalone version, it wouldn't actually create it. It just needed some single quotes.

### CODE REVIEW

**Comment by code-asher** [comment]
The single quotes will prevent `$STANDALONE_INSTALL_PREFIX` from expanding, no?  So it would be passed literally and then expanded by the subcommand instead which does not have that variable so it would be blank.

**Comment by KozmikNano** [comment]
Closing, due to the fact this isnt needed

**Comment by KozmikNano** [comment]
> The single quotes will prevent `$STANDALONE_INSTALL_PREFIX` from expanding, no? So it would be passed literally and then expanded by the subcommand instead which does not have that variable so it would be blank.

Yeah, I don't know what I was thinking 😅

**Comment by code-asher** [comment]
Hahaha all good, shell semantics are nuts

**Pull request closed without merging**
