### PR TITLE
Update Code to 1.75.0

### LINKED ISSUE #5988: Not able to install CodeGPT in latest VS Code Server v4.9.1
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: Windows
- Remote OS: Windows
- Remote Architecture: SageMaker Studio
- `code-server --version`: v4.9.1

image

### Steps to Reproduce

1. Installed VS code server v4.9.1 on SageMaker Studio.
2. Tried installing "DanielSanMedium.dscodegpt" (Code GPT) in Code Server then I get the following error.

Error details: Can't install 'danielsanmedium.dscodegpt' extension because it is not compatible with the current version of code-server (version 1.73.1).

### Expected

Allow users to install Code GPT extension on VS Code Server and start asking Code GPT to return a code for a specific question.

### Actual

Tried installing "DanielSanMedium.dscodegpt" (Code GPT) in Code Server then I get the following error.

Error details: Can't install 'danielsanmedium.dscodegpt' extension because it is not compatible with the current version of code-server (version 1.73.1).

### Logs

_No response_

### Screenshot/Video

image

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

_No response_

### LINKED ISSUE #5995: [Feat]: Upgrade to vscode 1.75.0
## Are you interested in submitting a PR for this?
No

### PR DESCRIPTION
**Pull request by code-asher**
- getting-started.diff: The way to get an icon's class changed
- proxy-uri.diff: The product service is passed in so we can get the proxy URI from that now instead of passing it in separately.

Closes #5995 
Closes #5988

### CODE REVIEW

**Comment by benz0li** [comment]
`code-server-4.10.0-rc.0-linux-amd64.tar.gz` from [Release v4.10.0-rc.0](https://github.com/coder/code-server/releases/tag/v4.9.0-rc.0) is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2022.10.110`
*  `ms-python.python@2023.2.0`

---

Terminal is not rendered properly (`"terminal.integrated.gpuAcceleration": "auto"`) **in Safari**:

Terminal

Workaround: `"terminal.integrated.gpuAcceleration": "off"`

Most probably related to:

* https://github.com/microsoft/vscode/issues/163448
  * https://github.com/xtermjs/xterm.js/issues/4218

**Comment by code-asher** [comment]
@benz0li thank you!!  I will make a regular release tomorrow assuming no issues pop up.

**Comment by benz0li** [comment]
It is worth [updating Code to 1.75.1](https://github.com/coder/code-server/issues/6012) first.

Maybe the problem with Terminal rendering in Safari is resolved in this release.  
👉 It [does not mention](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22January+2023+Recovery%201%22+is%3Aclosed) it, but you never know...

I am happy to test again.

**Comment by benz0li** [comment]
@code-asher Consider taking a `.2`-release as base for a new code-server release.
ℹ️ `.0`-releases have had some fundamental bugs.

i.e.

1. use the `.1`-release as base for a _release candidate_ (RC)
2. test, debug and fix; maybe do another RC-release
3. update codebase to the `.2`-release
4. test, debug and fix
5. release

**Comment by code-asher** [comment]
@benz0li That makes sense to me.  I will get us updated to 1.75.1 today.  

Starting with `.1` sounds good to me if it makes things easier.  I will do that going forward.

**Comment by benz0li** [comment]
@bala I do not recommend deploying a release candidate to a production server.

**Comment by code-asher** [comment]
Published the next release candidate with 1.75.1!

**Comment by benz0li** [comment]
`code-server-4.10.0-rc.1-linux-amd64.tar.gz` from [Release v4.10.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.10.0-rc.1) is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2022.10.110`
*  `ms-python.python@2023.2.0`

---

Terminal is still not rendered properly (`"terminal.integrated.gpuAcceleration": "auto"`) **in Safari**

---

Maybe @Tyriar knows more about why something like this is happening ([again](https://github.com/coder/code-server/pull/5535)) with Safari.  
ℹ️ My client: macOS version 13.2 (Ventura), Safari version 16.3 (18614.4.6.1.5)

@Tyriar: I have whitelisted your GitHub user at https://coder.jupyter.b-data.ch/ so you may have a look at it yourself.

**Comment by Tyriar** [comment]
We disable the webgl renderer on Safari still when it's auto. Break here to see what's happening:

https://github.com/microsoft/vscode/blob/c9753ca41c29f4d7aff568aa9159ee021b3c9307/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L364-L366

**Comment by benz0li** [comment]
> We disable the webgl renderer on Safari still when it's auto.

I am aware of that. (We already discussed this last year)

---

This was announced with Code v1.75:

> # January 2023 (version 1.75)
> 
> [...]
> 
> ## Terminal
> 
> [...]
> 
> ### [Powerline triangle and diagonal line custom glyphs](https://code.visualstudio.com/updates/v1_75#_powerline-triangle-and-diagonal-line-custom-glyphs)  
> GPU-accelerated terminals now get pixel-perfect custom glyphs for the triangle and diagonal line [Powerline](https://powerline.readthedocs.io/) extra symbols glyphs (U+E0B8-U+E0BF). These characters are ambiguous as to whether they are single or double width characters and differ depending on the font used, so we chose to render them as single width.
> 
> Before:
> 
> terminal-before-triangle
> 
> Triangles and diagonal line previously could display with bad anti-aliasing and odd borders
> 
> After:
> 
> terminal-after-triangle

---

In my case: Before (Code version: 1.73.1):

terminal_code-1 73 1

In my case: After (Code version: 1.75.1):

terminal_code-1 75 1

ℹ️ Font: [MesloLGS NF](https://github.com/romkatv/powerlevel10k/blob/master/font.md) (HiDPI display)

Cross references:

* https://github.com/xtermjs/xterm.js/issues/4258
* https://github.com/xtermjs/xterm.js/pull/4313

---

Interesting to read: [Powerlevel10k > Troubleshooting > Sub-pixel imperfections around powerline symbols](https://github.com/romkatv/powerlevel10k/blob/master/README.md#sub-pixel-imperfections-around-powerline-symbols)

`"terminal.integrated.customGlyphs": false` seems to have no effect while `"terminal.integrated.gpuAcceleration": "auto"`.

**Comment by benz0li** [comment]
Workaround on latest systems (Safari 16 and above): Enable Develop menu; Develop > User Agent: Choose either Microsoft Edge, Google Chrome or Firefox.

**Comment by Tyriar** [comment]
> In my case: After (Code version: 1.75.1):

That's tracked in https://github.com/xtermjs/xterm.js/issues/4120

**Pull request merged**
