### PR TITLE
change scope to subpath root instead of domain root so PWA will be installable on subpath

### LINKED ISSUE #5922: [Bug]: PWA is not installable when code-server is on subpath
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu 22.04
- Remote Architecture: AMD64
- `code-server --version`: 129500ee4c8ab7263461ffe327268ba56b9f210d

### Steps to Reproduce

1. Open code-server
2. No PWA app will be installable

### Expected

PWA app will be installable

### Actual

PWA app isn't installable

### Logs

_No response_

### Screenshot/Video

_No response_

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

_No response_

### PR DESCRIPTION
**Pull request by tobycm**
Fixes #5922

### CODE REVIEW

**Comment by code-asher** [comment]
I might be missing something.  This seems to do the opposite of the PR title?

**Comment by tobycm** [comment]
My bad guys. The service worker works, just the PWA is not installable.

**Comment by jsjoeio** [comment]
> My bad guys. The service worker works, just the PWA is not installable.

Ah got it. And does this fix that? I posted in the original issue that it works as expected on Coder so I think first we'd need steps to reproduce.

**Comment by tobycm** [comment]
I will reproduce this again when I got my Ubuntu Server up and running.

(don't know why it's failing installing GRUB 5 times in a row 😭 )

**Review by Ohhwshet — APPROVED** [review]

**Comment by code-asher** [comment]
@tobycm I am going to close the PR for inactivity but if you start working on it again we can re-open.

**Pull request closed without merging**
