### PR TITLE
Update Code to 1.82.3

### PR DESCRIPTION
**Pull request by benz0li**
Ping @code-asher: Security release

### CODE REVIEW

**Comment by benz0li** [comment]
`code-server-4.17.2-rc.1-linux-amd64.tar.gz` is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools-docker)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.7.100`
*  `ms-python.python@2023.16.0`

**Comment by benz0li** [comment]
IMHO no RC required. Just put out a proper release.

**Comment by code-asher** [comment]
This release is a bump to Electron which code-server does not use so I think we will not benefit from making a release honestly.

**Comment by benz0li** [comment]
> I think we will not benefit from making a release honestly.

Agreed.

**Comment by code-asher** [comment]
Ohh yeah that is a really good point.  We are going to release soon with 1.83.1 but I will keep that in mind for the future.

**Pull request merged**
