### PR TITLE
release: 4.0.0

### LINKED ISSUE #4176: release: 4.0.0
## Checklist

- [x] Assign to next release manager
- [x] Close previous release milestone
- [x] Create next release milestone
- [x] Associate issue with next release milestone

### LINKED ISSUE #4598: Patch configuring the display language
Previously, we supported the ability to [configure the Display Language](https://code.visualstudio.com/docs/getstarted/locales). As a result of switching to VS Code's upstream server, we have lost this feature with the 4.0.0 upgrade.

## Does it work upstream?

Apparently, no. If you go to vscode.dev and try to install a language pack, you get the following error messages:
image

Same with Codespaces
image

## How did it work before in code-server?

I believe we had to patch it to get it to work. We can investigate readding the patch, or even submitting a patch upstream to get this functionality both in code-server and vscode.dev/Codespaces

### PR DESCRIPTION
**Pull request by jsjoeio**
This PR is to generate a new release of `code-server` at `4.0.0`.

## Screenshot

image

## TODOs

Since this is a major release with breaking changes, we need to take extra steps to test it.

### How to Test 

1. Wait for [CI](https://github.com/cdr/code-server/actions/runs/1560705703) to finish.
2. Download artifcat: `release-packages`
3. Untar locally:
```shell
# Linux
cd release-packages && tar -xzf code-server*-linux-amd64.tar.gz
# macOS
cd release-packages && tar -xzf code-server*-macos-amd64.tar.gz
```
4. Run locally:
```shell
# Linux
./code-server*-linux-amd64.tar.gz./code-server
#macOS
./code-server*-macos-amd64.tar.gz/code-server
```

### Before Release
- [x] prep release notes @jsjoeio 
- [x] attach artifacts to release @jsjoeio 
- [x] built-in extensions @jsjoeio 
- [x] install extension @jsjoeio 
- [x] terminal @bpmct 
- [x] display language @jsjoeio 
- [x] debugging @code-asher 
- [x] pwa @bpmct 
- [x] make sure all the various routes all work (/, /vscode, /vscode/) @code-asher 
- [x] heartbeat @code-asher 
- [x] double-check reverse proxy (although this should be good) @jsjoeio 
- [x] double-check assets are properly cached @code-asher 
- [x] vs code cli commands like install-extension work @bpmct 
- [x] double-check the web sockets are including the type query param @code-asher 
- [x] github auth (actually did we ever add this back?) @jsjoeio 
- [x] fix plugin tests @code-asher 
- [x] reproduce the extensions issue @bpmct found then document in issue
- [x] #4598 with incoming PR @code-asher~~ pushed to 4.0.1
- [x] rebase PR and re-attach assets afterwards @jsjoeio 

### After Release
- [x] publish release and merge PR
- [x] ~~update the AUR package~~ this is a pre-release which means released to GitHub only so no npm, docker or aur packages will be updated

Fixes #4176

### CODE REVIEW

**Review by code-asher — APPROVED** [review]

**Comment by jsjoeio** [comment]
It appears we have lost our patch for changing the display language. Opened an issue to track: https://github.com/cdr/code-server/issues/4598

**Comment by jsjoeio** [comment]
GitHub Auth works!

How I tested:
1. Install GitHub Pull Requests and Issues Extension
2. Sign in using PAT
3. Create [PR](https://github.com/jsjoeio/github-email-extension/pull/1)

**Comment by bpmct** [comment]
bugs found:
- `code-server [foldername]` or `code-server -r [foldername]` does not work to open a folder. strangely, it works fine with files
- popular extensions are not recommended if user has 0 extensions installed (3.12.0 seemed to unfold this tab)
    Screen Shot 2021-12-09 at 2 49 25 PM

Everything else works great. Tested on OSX

**Comment by jsjoeio** [comment]
> code-server [foldername] or code-server -r [foldername] does not work to open a folder. strangely, it works fine with files

Great catch by @bpmct! @code-asher fixed this in https://github.com/cdr/code-server/pull/4599

> popular extensions are not recommended if user has 0 extensions installed (3.12.0 seemed to unfold this tab)

Tracking here: https://github.com/cdr/code-server/issues/4600

**Pull request merged**
