### PR TITLE
release: 4.6.0

### PR DESCRIPTION
**Pull request by code-asher**

### CODE REVIEW

**Comment by balajib-b** [comment]
this release is for today? - 17th August?

**Comment by code-asher** [comment]
Well today we will have a release candidate but the actual release may be in a few days or so depending on if any problems are found.

**Comment by jsjoeio** [comment]
I've tested this locally. Tried extensions, vim, terminal, editor, Jupyter and language (Spanish). All looks good 👍🏼

image

**Comment by bala** [comment]
image
installed successfully

**Review by jsjoeio — APPROVED** [review]

**Pull request merged**
