### PR TITLE
"HOST" environment variable

### LINKED ISSUE #6422: [Feat]: Set the host address with environment variable
## What is your suggestion?
It would be nice if we could set the host address with an environment variable, just as like as the port.

## Why do you want this feature?
There is a [docker-based project](https://github.com/linuxserver/docker-code-server), and I can change the listening port by using environment variable, but I can't change the address because it does not use environment variable. My container have it's own IPv6 address and I would like to bind to it with port 80. Currently I can't access the server with ipv6 address because it listens on `0.0.0.0` (ipv4 only).

## Are there any workarounds to get this functionality today?
I haven't found a solution yet, but I'm on it.

## Are you interested in submitting a PR for this?
Yes, that's why I'm opening this issue.

### PR DESCRIPTION
**Pull request by Cyanoure**
Hi!
I added the "HOST" environment variable. It works the same way as the "PORT".
I also added tests for it depending on "PORT" tests.

Fixes #6422

### CODE REVIEW

**Review by code-asher — COMMENTED** [review]
Thank you!  I love the addition of tests as well.

What do you think about making this `CODE_SERVER_HOST` instead?  I know we already have plain `PORT` but we are trying to ensure new variables have unique names.

**Comment by Cyanoure** [comment]
> Thank you! I love the addition of tests as well.
> 
> What do you think about making this `CODE_SERVER_HOST` instead? I know we already have plain `PORT` but we are trying to ensure new variables have unique names (and eventually we should add `CODE_SERVER_PORT` and deprecate `PORT` too).

I think it will be fine.
But for the port, I don't know. I mean, in the past when I tried Heroku, it used `PORT`. I had to use that environment variable to set the listening port of my nodejs server.
I don't know if anyone uses code-server in an environment like that.

Thanks for the review!

**Comment by code-asher** [comment]
Thank you for the input and the examples!  Collisions like that are a really good reason we should use a unique prefix.

For this PR let us go forward with `CODE_SERVER_HOST`, then.  No need to make any changes to `PORT` here (unless you want to), I can do that in another PR.

**Comment by code-asher** [comment]
Oh wait, were you saying that Heroku sets `PORT` so we actually should keep `PORT`?  I think I misunderstood as Heroku itself using `PORT` and that colliding with code-server.

**Comment by Cyanoure** [comment]
> Oh wait, were you saying that Heroku sets `PORT` so we actually should keep `PORT`? I think I misunderstood it as Heroku itself using `PORT` and that was colliding with code-server.

Yes :D 
I'm sorry if I was unclear.

Then I'll add a new commit for replacing `HOST` to `CODE_SERVER_HOST`.

**Review by code-asher — APPROVED** [review]
Thanks again, looks good!

Sounds like we will probably want to keep `PORT` around then.  I will keep that in mind!

**Pull request merged**
