### PR TITLE
🔧 Change config directory from `.config` to `.local`

### PR DESCRIPTION
**Pull request by bdsoha**
Updated `docker` documentation to use correct path locations.

### CODE REVIEW

**Comment by code-asher** [comment]
I wonder if we want both?  `.config` contains a config.yaml file code-server reads on startup.

**Comment by bdsoha** [comment]
> I wonder if we want both? `.config` contains a config.yaml file code-server reads on startup.

I personally moved the file to `/etc/coder/config.yaml` to better conform with Linux conventions.

**Comment by code-asher** [comment]
Fair, but `/etc` configuration tends to be world-readable and it may contain a password.

**Comment by bdsoha** [comment]
> Fair, but `/etc` configuration tends to be world-readable and the `config.yaml` may contain a password.

I agree with your comment.
For my specific orchestration, the password is not contained in the config file.

**Comment by code-asher** [comment]
Makes sense!  For the installation docs Iwhat do you think about keeping the `-v "$HOME/.config:/home/coder/.config" \` but also adding `-v "$HOME/.local:/home/coder/.local" \` so both the config and data are persisted outside the container?

**Comment by code-asher** [comment]
_ince there is a comment above about `.config` we may want to make mention of what `.local` is as well.

**Comment by bdsoha** [comment]
> Makes sense! For the installation doc example what do you think about keeping the `-v "$HOME/.config:/home/coder/.config" \` but also adding `-v "$HOME/.local:/home/coder/.local" \` so both the config and data are persisted outside the container?

VSCode doesn't use both paths.
If your goal is to also externally store and mount *user-configs* and *user-packages*, then yes.
Otherwise, IMO, I would just stick with the relevant path where VSCode's `settings.json` is stored.

**Comment by code-asher** [comment]
> VSCode doesn't use both paths.

Right, but code-server does.

Is there a situation where you would not want to mount that config when copy-pasting this command?  Not doing so means that every time you restart the container your config is reset and a new password is generated.

**Review by code-asher — APPROVED** [review]
Thank you!

**Pull request merged**
