### PR TITLE
feat(testing): add test for optionDescriptions

### LINKED ISSUE #4915: [Testing]: write tests for optionDescriptions
We're missing coverage for L240-260 in `src/node/cli.ts`:

https://github.com/coder/code-server/blob/main/src/node/cli.ts#L239-L266

Fix this by writing a couple tests for: `optionDescriptions`

### PR DESCRIPTION
**Pull request by jsjoeio**
This PR adds a test for `optionDescriptions`.

Fixes #4915

### CODE REVIEW

**Review by code-asher — COMMENTED** [review]
What do you think about making `optionDescriptions` take an argument so we can test specific expectations?  And possibly adding `optionDescription` so we can test a single option without having to wrap it in an array.

For example:

```
it("should display option flag and description", () => {
  expect(optionDescription({ type: "boolean": long: "foo", short: "f", description: "a foo flag")}).toStrictEqual("-f --foo a foo flag")
})

it("should visually align multiple options", () => {
  const options = [
    { type: "boolean": long: "foo", short: "f", description: "a foo flag"}
    { type: "string": short: "r", description: "an r flag"}
    { type: "string[]": long: "bar"}
  ]
  expect(optionDescriptions(options)).toStrictEqual([
    "-f --foo foobar",
    "-r       radio"
    "   --bar"
  ].join("\n")
})

it("should add all valid options for enumerated types", () => {
  expect(optionDescription({ type: AuthType: long: "auth", description: "some auth")}).toStrictEqual("   --foo some auth [password, none]")
})

it("should show if an option is deprecated")

it("should show newlines in description")
```

**Comment by jsjoeio** [comment]
@code-asher okay to be extra clear, you're saying I should do this:

> What do you think about making optionDescriptions take an argument so we can test specific expectations?

and not do this: 

>  single-option function is pretty much useless

right?

**Comment by code-asher** [comment]
Yes!

**Review by code-asher — APPROVED** [review]
Nicely done!

**Pull request merged**
