### PR TITLE
chore: update code to 1.70.2

### LINKED ISSUE #5470: [Feat]: Upgrade vscode to 1.70.2
## What is your suggestion?
Upgrade vscode to 1.70.2

### PR DESCRIPTION
**Pull request by fritterhoff**
Fixes #5470

## How to test locally

1. clone, update submodule, and install deps
```shell
gh pr checkout 5485  && git submodule update --init && quilt push -a && yarn
```
2. run locally: 
```sh
yarn watch
```
3. open [localhost:8080](http://localhost:8080) 
4. test basic functions - open files, terminal, etc.

### CODE REVIEW

**Comment by jsjoeio** [comment]
@fritterhoff thank you! do the patches need to be updated/refreshed?

**Comment by fritterhoff** [comment]
Nope. No changes required.

**Comment by jsjoeio** [comment]
Amazing! I'll checkout locally and test. Also requesting review from @code-asher - once we both ✅, we can merge.

**Comment by jsjoeio** [comment]
>   1) [Chromium] › extensions.test.ts:8:3 › Extensions › should have access to VSCODE_PROXY_URI =====

We know this test is flakey. https://github.com/coder/code-server/pull/5481 should reduce that a bit.

**Comment by jsjoeio** [comment]
All looks good. I did notice a weird flash of the terminal prompt but I don't know if that's related to `zsh` or my think  🤔 anyone else see this?

https://user-images.githubusercontent.com/3806031/185979297-2e884cce-9667-4a72-bdea-0f3c66c08fab.mov

**Comment by code-asher** [comment]
I am not seeing my prompt doing that (using Bash).  My guess is it is either ZSH or the predictive output but probably unrelated to this PR.

**Review by code-asher — APPROVED** [review]

**Comment by code-asher** [comment]
Actually maybe they did change something...when I run ZSH there is a slight flash after all but not with 4.6.0.  Weird.

**Comment by code-asher** [comment]
Ah nevermind I see it on 4.6.0 as well, just at a different frequency.

**Review by jsjoeio — APPROVED** [review]

**Pull request merged**
