### PR TITLE
Update Code to 1.77.1

### LINKED ISSUE #6104: [Feat]: Upgrade to vscode 1.76.2

### PR DESCRIPTION
**Pull request by code-asher**
Closes #6104

### CODE REVIEW

**Comment by benz0li** [comment]
`code-server-4.12.0-rc.1-linux-amd64.tar.gz` from [Release v4.12.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.12.0-rc.1) is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

---

Jupyter Notebooks do **not** work.

*  `ms-toolsai.jupyter@2023.3.100`
*  `ms-python.python@2023.6.0`

Output in browser console:

```
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “vscode-remote+coder-002ejupyter-002eb-002ddata-002ech.vscode-resource.vscode-cdn.net”, which could put your confidential information at risk. (ipywidgetsKernel.js.map, line 0)
```

---

Terminal is not rendered properly **in Safari** because of https://github.com/xtermjs/xterm.js/issues/4120.  
ℹ️ Workaround: `"terminal.integrated.gpuAcceleration": "off"`.
👉 Fix is coming in Code 1.78 with PR https://github.com/microsoft/vscode/pull/178443.

**Comment by code-asher** [comment]
Hmm interesting, that specific error is not showing for me but when I try to run something it pops up a "select kernel" dialog that never completes.  Investigating...

**Comment by code-asher** [comment]
Might be an issue with APIs having updated and the Jupyter extension being too old on Open VSX...https://github.com/VSCodium/vscodium/issues/1460 (seems to be incorrectly published).

Probably will have to wait until that updates before releasing.

**Comment by benz0li** [comment]
> Probably will have to wait until that updates before releasing.

The extension has been re-published: https://github.com/open-vsx/publish-extensions/issues/674

**Comment by code-asher** [comment]
Awesome!  Will put out a new RC right away.

**Comment by benz0li** [comment]
`code-server-4.12.0-rc.2-linux-amd64.tar.gz` from [Release v4.12.0-rc.2](https://github.com/coder/code-server/releases/tag/v4.12.0-rc.2) is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools)`.

Jupyter Notebooks are now working.

*  `ms-toolsai.jupyter@2023.3.100`[^1]
*  `ms-python.python@2023.6.1`

[^1]: Republished version from 2023-04-20

**Pull request merged**
