### PR TITLE
Update Code to 1.95.3

### PR DESCRIPTION
**Pull request by benz0li**

### CODE REVIEW

**Comment by benz0li** [comment]
Ping @code-asher 

P.S.: Please fix links in https://github.com/coder/code-server/commit/9a5726f2501c738e4821d8f250d4d032673ba673 (both pointing to v4.93.1).

**Comment by code-asher** [comment]
> Please fix links

Oops, thanks for pointing that out.

**Review by code-asher — APPROVED** [review]
Thank you!

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Need support


benz0li:code-1.95.3

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Thanks

**Pull request merged**
