### PR TITLE
Update Code to 1.79.1

### PR DESCRIPTION
**Pull request by code-asher**
Mostly just the usual shifting or changing of the surrounding context but I did refactor the getting started block we insert because it keeps getting mangled on each update.  Instead of shifting things around the columns I just prepend it to the right column.

Closes https://github.com/coder/code-server/issues/6257

### CODE REVIEW

**Comment by code-asher** [comment]
Getting 404s on some vsda module but everything seems to work without it and I do not see it referenced in the package.json so maybe it is optional.

**Comment by code-asher** [comment]
Here we go: https://github.com/coder/code-server/tree/v4.14.0-rc.1

**Comment by code-asher** [comment]
GitHub release will take a bit longer, then assuming nothing goes wrong we will promote the RC tomorrow or so.

**Comment by code-asher** [comment]
By the way you may have already come up with a good way to run that postinstall script but if not I wonder if we can edit the `find`.  Currently it is `find ./lib/vscode -path "*node_modules" ` so maybe something like `find ./lib/vscode -path "*node_modules" -or -path "*extensions"` to include the extensions directory could work?

**Comment by drupol** [comment]
So basically, the idea is to alter this line only?

https://github.com/NixOS/nixpkgs/blob/8a3054c4f31ffa22ad4cca22a8aa271c59ccc91d/pkgs/servers/code-server/default.nix#L235

**Comment by code-asher** [comment]
Yup, exactly.

**Comment by drupol** [comment]
I'll do it within the update then.

**Comment by code-asher** [comment]
We still need to do something about the commit, too.  Looks like it used to be a hardcoded variable so maybe we do that again: https://github.com/NixOS/nixpkgs/blob/5e1324e48a7a05e150f7d05489dfb7507a29d87e/pkgs/servers/code-server/default.nix#L17

Or maybe there is some better way to automatically get the commit.

**Comment by code-asher** [comment]
Hmm actually the `find` command I proposed does not seem to work with whatever that `-prune` flag is doing so we might need to duplicate the `find` to install things from the `extensions` directory or maybe there is some clever way to get it working in one command.

**Comment by drupol** [comment]
I'm not the person who did that NixOS module and I have absolutely no clue into it, I'm just willing to update it.

Do you mind submitting a PR against `NixOS/nixpkgs` to fix this and also add you as maintainer?

**Comment by drupol** [comment]
Ping me when it's done so I can take care of the PR myself :)

**Comment by benz0li** [comment]
@code-asher I will deploy v4.14.0-rc.1 within the next hour and do the usual smoke tests.

**Comment by benz0li** [comment]
@code-asher Is there only the source code for v4.14.0-rc.1? No other assets?

**Comment by benz0li** [comment]
P.S.: 1.79.2 released.

**Comment by code-asher** [comment]
@benz0li Oh no hmm...something must have gone wrong with the build job.

**Comment by code-asher** [comment]
I might as well throw in 1.79.2 first.

**Comment by code-asher** [comment]
Weird, I used their `release/1.79` branch for this PR and apparently that was already 1.79.2, they just had not tagged it yet.

Looking into the build issue now.

**Comment by code-asher** [comment]
Turns out the job is fine, I just somehow completely forgot that we have to manually run the "draft release" workflow.  Really need to automate that at some point.  :facepalm: 

Assets are attached now.

**Comment by benz0li** [comment]
`code-server-4.14.0-rc.1-linux-amd64.tar.gz` from [Release v4.14.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.14.0-rc.1) is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools-docker)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.3.100`
*  `ms-python.python@2023.10.1`

**Pull request merged**
