### PR TITLE
#5374 make requirements clear

### LINKED ISSUE #5374: [Docs]: Requirements clearification
## What is your suggestion?
In the requirements section of the README.md stands `TL;DR: Linux machine with WebSockets enabled, 1 GB RAM, and 2 CPUs`
But I think most machines do not have 2 CPUs. They have CPU-Cores.
## How will this improve the docs?
Clearification of requirements
## Are you interested in submitting a PR for this?
yes

### PR DESCRIPTION
**Pull request by BelphegorPrime**
Fixes  #5374

### CODE REVIEW

**Comment by code-asher** [comment]
I wonder if we should say `vCPU`?  I see that terminology in Google Cloud and AWS.

**Review by code-asher — CHANGES_REQUESTED** [review]
Just marking this PR as changes requested while we talk about the terminology.

**Comment by jsjoeio** [comment]
Agreed, `vCPU` makes more sense.

**Comment by jsjoeio** [comment]
image

I don't have permission to push to your branch so I'm going to close and open a new PR

**Pull request closed without merging**
