### PR TITLE
Update Code to 1.83.1

### PR DESCRIPTION
**Pull request by benz0li**
Fixes https://github.com/coder/code-server/issues/6475

### CODE REVIEW

**Comment by benz0li** [comment]
Ping @code-asher.

Please review and let the checks run.

Should the Safari error still occur: Please resolve.

Thank you.

**Comment by benz0li** [comment]
`code-server-4.18.0-rc.1-linux-amd64.tar.gz` is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools-docker)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.9.100`
*  `ms-python.python@2023.18.0`

**Comment by code-asher** [comment]
I need to fix those checks so they run for repeat contributors.

If Safari is still an issue I should be able to fix to it this week.

**Review by code-asher — APPROVED** [review]

**Comment by benz0li** [comment]
@code-asher I have also *smoke-tested* `code-server-4.18.0-rc.1-linux-amd64.tar.gz` from https://github.com/coder/code-server/releases/tag/v4.18.0-rc.1.

Same (positive) results as https://github.com/coder/code-server/pull/6488#issuecomment-1762993871.

**Comment by code-asher** [comment]
Awesome, thank you.  I think I will promote the release today.

**Pull request merged**
