### PR TITLE
Update Code to 1.88.1

### PR DESCRIPTION
**Pull request by benz0li**
Ping @code-asher

### CODE REVIEW

**Comment by benz0li** [comment]
@code-asher Please re-run. My local build was successful.

**Comment by code-asher** [comment]
Weird, I ran it a couple times but it keeps getting `ENOENT`.

Oh...I think I know why.  Something about `node-gyp` being removed from npm.  We updated Node to 18.18.2, but it did not trigger a rebuild of VS Code because of the cache (which itself is a bug I will have to fix), so it is only now causing an issue.

Might work to install `node-gyp` globally, let me test it later today and see.

**Review by code-asher — APPROVED** [review]

**Comment by benz0li** [comment]
@code-asher What about the failed e2e tests?: https://github.com/coder/code-server/actions/runs/8698237868

**Comment by code-asher** [comment]
Ah yeah I was worried about that, looks like the Express update broke something.

Not to worry though, the commit that was actually released is https://github.com/coder/code-server/commit/9a28bc29dbddb6886dfe03dc1c31320249a901ce which did pass, that commit was just for updating the changelog and Helm chart afterward.

**Comment by code-asher** [comment]
Fixed!

**Pull request merged**
