### PR TITLE
Update Code to 1.83.0

### LINKED ISSUE #6475: [Feat]: Update Code to 1.83
## What is your suggestion?

Update Code to 1.83

### PR DESCRIPTION
**Pull request by benz0li**
Fixes #6475

### CODE REVIEW

**Comment by benz0li** [comment]
`code-server-4.18.0-rc.1-linux-amd64.tar.gz` is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools-docker)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.9.100`
*  `ms-python.python@2023.16.0`

**Comment by benz0li** [comment]
@code-asher Let us use this `.0`-releases as base for a _release candidate_ (RC) and wait for a `.1`/`.2`-release as base for a _new_ release.

**Comment by code-asher** [comment]
Makes sense to me, will do!  Thank you for taking care of this.

**Review by code-asher — APPROVED** [review]

**Comment by code-asher** [comment]
Looks like we have another Safari error, looks like a regular expression that it does not support.  I think we will probably need to patch it.

**Comment by benz0li** [comment]
VS Code 1.83.1 was released yesterday: https://code.visualstudio.com/updates/v1_83

**Pull request closed without merging**
