### PR TITLE
Update VS Code 1.95

### PR DESCRIPTION
**Pull request by code-asher**
Closes https://github.com/coder/code-server/issues/7052

### CODE REVIEW

**Comment by bcpeinhardt** [comment]
It got merged while I was reviewing 💀 My only comment was gonna be "so many hashes" haha.

**Comment by bcpeinhardt** [comment]
Also funny that minification respects the export alias.

**Comment by code-asher** [comment]
My bad did not realize you were reviewing!!  I will need to get used to not just wild-west merging here lol

> Also funny that minification respects the export alias.

Haha yeah, honestly a relief because otherwise we would have to do some crazy things like import it as `$6F` or whatever name it choose

**Comment by benz0li** [comment]
Ping @code-asher: `code-server-4.95.1-rc.1-linux-amd64.tar.gz` with Code 1.95.1 is deployed at https://coder.jupyter.b-data.ch.

* Issue https://github.com/coder/code-server/issues/7042 still persists
* Rendering of Nerd Font's glyphs and symbols seem to work properly now

**Comment by benz0li** [comment]
Ping @code-asher: `code-server-4.95.1-rc.2-linux-amd64.tar.gz` with Code 1.95.1 is deployed at https://coder.jupyter.b-data.ch.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* web view

Workspaces and Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2024.10.0`
*  `ms-python.python@2024.18.0`

**Comment by benz0li** [comment]
`code-server` v4.95.1-rc.2 also resolves issue https://github.com/coder/code-server/issues/7042.

**Comment by benz0li** [comment]
*Unofficial* and *untested* RISC-V 64-bit (`riscv64`) and Power 64-bit (`ppc64le`) release assets are available at https://gitlab.b-data.ch/coder/code-server/-/releases/v4.95.1

**Pull request merged**
