### PR TITLE
Update Code to 1.81.0

### PR DESCRIPTION
**Pull request by benz0li**
Ping @code-asher

### CODE REVIEW

**Comment by benz0li** [comment]
`code-server-4.17.0-rc.1-linux-amd64.tar.gz` is deployed at https://coder.jupyter.b-data.ch; Image `R (base:test-devtools-docker)`.

Functionality [modified by patches] tested and found to work:

* base-path
* cli-window-open
* local-storage
* marketplace
* proxy-url
* service-worker
* webview

Jupyter Notebooks also work fine:

*  `ms-toolsai.jupyter@2023.3.100`
*  `ms-python.python@2023.12.0`

**Comment by benz0li** [comment]
Notable commits affecting patches:

* https://github.com/microsoft/vscode/commit/322bc2d7d86e8d0c2ccb1bfdabe594e2011d500f
  * File: `lib/vscode/src/vs/code/browser/workbench/workbench.ts`
  * Patches: `base-path.diff`, `proxy-uri.diff`
* https://github.com/microsoft/vscode/commit/ef42b49e806b4a4f1202ec2e31f441465a7047de
  * File: `lib/vscode/src/vs/server/node/serverServices.ts`
  * Patch: `telemetry.diff`

**Comment by code-asher** [comment]
Thank you!  I am not sure why CI keeps requiring approval; I thought we had that for first-time contributors only so we will have to look into that.

Seems CI is experiencing a build error, I have not looked into it yet but I am going to re-run it in case it is ephemeral.

**Comment by code-asher** [comment]
Re-running did not work, and it fails for me locally as well.  I wonder if there is some newly required dependency.

**Comment by benz0li** [comment]
> Re-running did not work, and it fails for me locally as well. I wonder if there is some newly required dependency.

The problem:

```
make: Entering directory '/home/runner/work/code-server/code-server/lib/vscode/remote/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
In file included from ../src/kerberos_common.h:5,
                 from ../src/kerberos.h:12,
                 from ../src/kerberos.cc:1:
../src/unix/kerberos_gss.h:21:14: fatal error: gssapi/gssapi.h: No such file or directory
   21 |     #include <gssapi/gssapi.h>
      |              ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [kerberos.target.mk:114: Release/obj.target/kerberos/src/kerberos.o] Error 1
```

@code-asher Is `libkrb5-dev` installed?

**Comment by code-asher** [comment]
Thank you, `libkrb5-dev` did the trick!  I suppose we will need to update CI and the docs.

**Comment by benz0li** [comment]
ℹ️ [Prerequisites for Linux](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites) [have recently changed](https://github.com/microsoft/vscode/wiki/How-to-Contribute/_history).

**Comment by benz0li** [comment]
For the next release candidate and the release itself, I recommend waiting for Code 1.81.1.

**Comment by benz0li** [comment]
@code-asher Please update the CI and the docs in the meantime.

Thank you.

**Pull request closed without merging**
